use std::collections::BTreeMap;

use super::ids::{AttemptId, RequestId};

/// Downstream response mode exposed to a client.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DownstreamMode {
    /// Server-sent events or another streaming response.
    Streaming,
    /// Complete JSON response without downstream streaming.
    NonStreamJson,
    /// Local metadata/health response generated by this process.
    LocalMetadata,
}

impl DownstreamMode {
    /// Returns the stable storage label for this mode.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Streaming => "streaming",
            Self::NonStreamJson => "non-stream-json",
            Self::LocalMetadata => "local-metadata",
        }
    }
}

/// Upstream request mode used by a guarded attempt.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum UpstreamMode {
    /// Upstream streaming response.
    Streaming,
    /// Upstream complete JSON response.
    NonStreamJson,
    /// No upstream was contacted for this record.
    NotApplicable,
}

impl UpstreamMode {
    /// Returns the stable storage label for this mode.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Streaming => "streaming",
            Self::NonStreamJson => "non-stream-json",
            Self::NotApplicable => "not-applicable",
        }
    }
}

/// Final status for a downstream request.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RequestStatus {
    /// The downstream request completed successfully.
    Succeeded,
    /// The downstream request failed before a successful response.
    Failed,
    /// The downstream request was aborted or cancelled.
    Aborted,
}

impl RequestStatus {
    /// Returns the stable storage label for this status.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Succeeded => "succeeded",
            Self::Failed => "failed",
            Self::Aborted => "aborted",
        }
    }
}

/// Final status for one upstream attempt.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AttemptStatus {
    /// The upstream attempt completed successfully.
    Succeeded,
    /// The upstream attempt failed and did not produce a usable response.
    Failed,
    /// The upstream attempt was rejected and scheduled for retry.
    Retried,
    /// The upstream attempt was aborted or cancelled.
    Aborted,
}

impl AttemptStatus {
    /// Returns the stable storage label for this status.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Succeeded => "succeeded",
            Self::Failed => "failed",
            Self::Retried => "retried",
            Self::Aborted => "aborted",
        }
    }
}

/// Raw stream payload fragment captured in upstream arrival order.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RawPayloadChunk {
    /// Stable channel label for the fragment.
    pub channel: String,
    /// Raw fragment text after capture-boundary redaction.
    pub text: String,
}

impl RawPayloadChunk {
    /// Builds one raw stream fragment.
    #[must_use]
    pub fn new(channel: impl Into<String>, text: impl Into<String>) -> Self {
        Self {
            channel: channel.into(),
            text: text.into(),
        }
    }
}

/// Optional raw payload fragments that may be persisted only when configured.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct RawPayloads {
    /// Raw downstream request body or normalized prompt payload.
    pub input: Option<String>,
    /// Raw model output payload.
    pub output: Option<String>,
    /// Raw reasoning payload, when exposed by an upstream model.
    pub reasoning: Option<String>,
    /// Raw tool-call payload.
    pub tool_calls: Option<String>,
    /// Raw stream fragments in upstream arrival order.
    pub chunks: Vec<RawPayloadChunk>,
}

/// Metadata captured for one completed downstream request.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RequestRecord {
    /// Stable request id.
    pub request_id: RequestId,
    /// Request start time in Unix milliseconds.
    pub started_at_unix_ms: u64,
    /// Request finish time in Unix milliseconds.
    pub finished_at_unix_ms: Option<u64>,
    /// Downstream response mode.
    pub downstream_mode: DownstreamMode,
    /// Upstream mode used to serve the request.
    pub upstream_mode: UpstreamMode,
    /// OpenAI-compatible model id, if known.
    pub model_id: Option<String>,
    /// Normalized input fingerprint used for later loop/retry correlation.
    pub input_fingerprint: Option<String>,
    /// Final request status.
    pub status: RequestStatus,
    /// Downstream HTTP status, if an HTTP response was produced.
    pub http_status: Option<u16>,
    /// Failure reason visible to observability, if any.
    pub error_reason: Option<String>,
    /// Abort/cancellation reason, if any.
    pub abort_reason: Option<String>,
    /// Request-side headers and metadata.
    pub request_metadata: BTreeMap<String, String>,
    /// Response-side headers and metadata.
    pub response_metadata: BTreeMap<String, String>,
    /// Optional raw payload fragments.
    pub raw_payloads: RawPayloads,
}

/// Metadata captured for one upstream attempt.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AttemptRecord {
    /// Stable attempt id.
    pub attempt_id: AttemptId,
    /// Parent request id.
    pub request_id: RequestId,
    /// One-based attempt number.
    pub attempt_number: u32,
    /// Attempt start time in Unix milliseconds.
    pub started_at_unix_ms: u64,
    /// Attempt finish time in Unix milliseconds.
    pub finished_at_unix_ms: Option<u64>,
    /// Upstream mode used for this attempt.
    pub upstream_mode: UpstreamMode,
    /// Final attempt status.
    pub status: AttemptStatus,
    /// Upstream HTTP status, if one was received.
    pub http_status: Option<u16>,
    /// Failure reason, if any.
    pub error_reason: Option<String>,
    /// Retry reason, if this attempt led to a retry.
    pub retry_reason: Option<String>,
    /// Abort/cancellation reason, if any.
    pub abort_reason: Option<String>,
    /// Request-side upstream headers and metadata.
    pub request_metadata: BTreeMap<String, String>,
    /// Response-side upstream headers and metadata.
    pub response_metadata: BTreeMap<String, String>,
    /// Optional raw payload fragments.
    pub raw_payloads: RawPayloads,
}

/// Result of a store write after checking the current hot-reloadable settings.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum StoreWrite {
    /// The row was persisted.
    Written,
    /// `observability.enabled=false`, so the write was intentionally skipped.
    Disabled,
}

/// Current retention usage tracked by the `SQLite` store.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RetentionUsage {
    /// Number of request rows currently retained.
    pub request_count: u64,
    /// Number of attempt rows currently retained.
    pub attempt_count: u64,
    /// Total indexed observability records currently retained.
    pub record_count: u64,
    /// Actual `SQLite` page storage bytes.
    ///
    /// This includes `SQLite` schema, page, index, and freelist overhead. It can
    /// never shrink below the minimum empty database footprint for the active
    /// schema and page size.
    pub observed_bytes: u64,
}

/// Retention pruning counters persisted by the observability store.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct RetentionPruningStats {
    /// Number of retention-pruning passes that deleted at least one request.
    pub prune_events: u64,
    /// Number of request rows deleted by retention pruning.
    pub pruned_requests: u64,
    /// Number of attempt rows deleted by retention pruning.
    pub pruned_attempts: u64,
    /// Last pruning time in Unix milliseconds, if pruning has happened.
    pub last_pruned_at_unix_ms: Option<u64>,
}

/// Low-cardinality request-count metric row.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RequestMetricCount {
    /// Final request status label.
    pub status: String,
    /// Downstream response mode label.
    pub downstream_mode: String,
    /// Upstream response mode label.
    pub upstream_mode: String,
    /// Downstream HTTP status class label.
    pub http_status_class: String,
    /// Row count.
    pub count: u64,
}

/// Low-cardinality attempt-count metric row.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AttemptMetricCount {
    /// Final attempt status label.
    pub status: String,
    /// Upstream response mode label.
    pub upstream_mode: String,
    /// Upstream HTTP status class label.
    pub http_status_class: String,
    /// Row count.
    pub count: u64,
}

/// Low-cardinality upstream-error metric row.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct UpstreamErrorMetricCount {
    /// Error kind bucket.
    pub kind: String,
    /// Upstream HTTP status class label.
    pub http_status_class: String,
    /// Row count.
    pub count: u64,
}

/// Low-cardinality heartbeat-mode metric row.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct HeartbeatModeMetricCount {
    /// Observed heartbeat/liveness mode.
    pub mode: String,
    /// Row count.
    pub count: u64,
}

/// One cumulative histogram bucket.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct HistogramBucket {
    /// Inclusive upper bound in milliseconds.
    pub le_ms: u64,
    /// Cumulative value count up to and including `le_ms`.
    pub count: u64,
}

/// Histogram snapshot over millisecond latency values.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LatencyHistogram {
    /// Cumulative finite buckets.
    pub buckets: Vec<HistogramBucket>,
    /// Total number of observed values.
    pub count: u64,
    /// Sum of observed values in milliseconds.
    pub sum_ms: u64,
}

/// Prometheus-oriented aggregate metrics derived from retained observations.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ObservabilityMetricsSnapshot {
    /// Request rows grouped by low-cardinality lifecycle labels.
    pub request_counts: Vec<RequestMetricCount>,
    /// Attempt rows grouped by low-cardinality lifecycle labels.
    pub attempt_counts: Vec<AttemptMetricCount>,
    /// Attempts that were retried or recorded a retry reason.
    pub retry_count: u64,
    /// Attempts or requests aborted by loop protection.
    pub loop_abort_count: u64,
    /// Upstream errors grouped into bounded buckets.
    pub upstream_error_counts: Vec<UpstreamErrorMetricCount>,
    /// First-token latency histogram from shielded attempts when present.
    pub first_token_latency_ms: LatencyHistogram,
    /// End-to-end request latency histogram.
    pub total_latency_ms: LatencyHistogram,
    /// Observed heartbeat/liveness modes.
    pub heartbeat_mode_counts: Vec<HeartbeatModeMetricCount>,
    /// Current retention usage.
    pub retention_usage: RetentionUsage,
    /// Persisted pruning counters.
    pub pruning: RetentionPruningStats,
}

/// Safe bounded request summary for gated debug endpoints.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DebugRequestSummary {
    /// Stable request id.
    pub request_id: String,
    /// Request start time in Unix milliseconds.
    pub started_at_unix_ms: u64,
    /// Request finish time in Unix milliseconds.
    pub finished_at_unix_ms: Option<u64>,
    /// Request duration in milliseconds.
    pub duration_ms: Option<u64>,
    /// Downstream response mode.
    pub downstream_mode: String,
    /// Upstream response mode.
    pub upstream_mode: String,
    /// Sanitized model id, if known.
    pub model_id: Option<String>,
    /// Final request status.
    pub status: String,
    /// Downstream HTTP status, if one was produced.
    pub http_status: Option<u16>,
    /// Sanitized failure reason, if any.
    pub error_reason: Option<String>,
    /// Sanitized abort reason, if any.
    pub abort_reason: Option<String>,
    /// Number of attempts associated with the request.
    pub attempt_count: u64,
    /// Number of retried attempts associated with the request.
    pub retry_count: u64,
    /// Whether loop protection was observed for this request.
    pub loop_detected: bool,
    /// Redacted and filtered request metadata.
    pub request_metadata: BTreeMap<String, String>,
    /// Redacted and filtered response metadata.
    pub response_metadata: BTreeMap<String, String>,
}
