use std::collections::BTreeMap;

use super::ids::{AttemptId, RequestId};

/// Downstream response mode exposed to a client.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DownstreamMode {
    /// Server-sent events or another streaming response.
    Streaming,
    /// Complete JSON response without downstream streaming.
    NonStreamJson,
    /// Local metadata/health response generated by this process.
    LocalMetadata,
}

impl DownstreamMode {
    /// Returns the stable storage label for this mode.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Streaming => "streaming",
            Self::NonStreamJson => "non-stream-json",
            Self::LocalMetadata => "local-metadata",
        }
    }
}

/// Upstream request mode used by a guarded attempt.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum UpstreamMode {
    /// Upstream streaming response.
    Streaming,
    /// Upstream complete JSON response.
    NonStreamJson,
    /// No upstream was contacted for this record.
    NotApplicable,
}

impl UpstreamMode {
    /// Returns the stable storage label for this mode.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Streaming => "streaming",
            Self::NonStreamJson => "non-stream-json",
            Self::NotApplicable => "not-applicable",
        }
    }
}

/// Final status for a downstream request.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RequestStatus {
    /// The downstream request completed successfully.
    Succeeded,
    /// The downstream request failed before a successful response.
    Failed,
    /// The downstream request was aborted or cancelled.
    Aborted,
}

impl RequestStatus {
    /// Returns the stable storage label for this status.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Succeeded => "succeeded",
            Self::Failed => "failed",
            Self::Aborted => "aborted",
        }
    }
}

/// Final status for one upstream attempt.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AttemptStatus {
    /// The upstream attempt completed successfully.
    Succeeded,
    /// The upstream attempt failed and did not produce a usable response.
    Failed,
    /// The upstream attempt was rejected and scheduled for retry.
    Retried,
    /// The upstream attempt was aborted or cancelled.
    Aborted,
}

impl AttemptStatus {
    /// Returns the stable storage label for this status.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Succeeded => "succeeded",
            Self::Failed => "failed",
            Self::Retried => "retried",
            Self::Aborted => "aborted",
        }
    }
}

/// Optional raw payload fragments that may be persisted only when configured.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct RawPayloads {
    /// Raw downstream request body or normalized prompt payload.
    pub input: Option<String>,
    /// Raw model output payload.
    pub output: Option<String>,
    /// Raw reasoning payload, when exposed by an upstream model.
    pub reasoning: Option<String>,
    /// Raw tool-call payload.
    pub tool_calls: Option<String>,
}

/// Metadata captured for one completed downstream request.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RequestRecord {
    /// Stable request id.
    pub request_id: RequestId,
    /// Request start time in Unix milliseconds.
    pub started_at_unix_ms: u64,
    /// Request finish time in Unix milliseconds.
    pub finished_at_unix_ms: Option<u64>,
    /// Downstream response mode.
    pub downstream_mode: DownstreamMode,
    /// Upstream mode used to serve the request.
    pub upstream_mode: UpstreamMode,
    /// OpenAI-compatible model id, if known.
    pub model_id: Option<String>,
    /// Normalized input fingerprint used for later loop/retry correlation.
    pub input_fingerprint: Option<String>,
    /// Final request status.
    pub status: RequestStatus,
    /// Downstream HTTP status, if an HTTP response was produced.
    pub http_status: Option<u16>,
    /// Failure reason visible to observability, if any.
    pub error_reason: Option<String>,
    /// Abort/cancellation reason, if any.
    pub abort_reason: Option<String>,
    /// Request-side headers and metadata.
    pub request_metadata: BTreeMap<String, String>,
    /// Response-side headers and metadata.
    pub response_metadata: BTreeMap<String, String>,
    /// Optional raw payload fragments.
    pub raw_payloads: RawPayloads,
}

/// Metadata captured for one upstream attempt.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AttemptRecord {
    /// Stable attempt id.
    pub attempt_id: AttemptId,
    /// Parent request id.
    pub request_id: RequestId,
    /// One-based attempt number.
    pub attempt_number: u32,
    /// Attempt start time in Unix milliseconds.
    pub started_at_unix_ms: u64,
    /// Attempt finish time in Unix milliseconds.
    pub finished_at_unix_ms: Option<u64>,
    /// Upstream mode used for this attempt.
    pub upstream_mode: UpstreamMode,
    /// Final attempt status.
    pub status: AttemptStatus,
    /// Upstream HTTP status, if one was received.
    pub http_status: Option<u16>,
    /// Failure reason, if any.
    pub error_reason: Option<String>,
    /// Retry reason, if this attempt led to a retry.
    pub retry_reason: Option<String>,
    /// Abort/cancellation reason, if any.
    pub abort_reason: Option<String>,
    /// Request-side upstream headers and metadata.
    pub request_metadata: BTreeMap<String, String>,
    /// Response-side upstream headers and metadata.
    pub response_metadata: BTreeMap<String, String>,
    /// Optional raw payload fragments.
    pub raw_payloads: RawPayloads,
}

/// Result of a store write after checking the current hot-reloadable settings.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum StoreWrite {
    /// The row was persisted.
    Written,
    /// `observability.enabled=false`, so the write was intentionally skipped.
    Disabled,
}

/// Current retention usage tracked by the `SQLite` store.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RetentionUsage {
    /// Number of request rows currently retained.
    pub request_count: u64,
    /// Actual `SQLite` page storage bytes.
    ///
    /// This includes `SQLite` schema, page, index, and freelist overhead. It can
    /// never shrink below the minimum empty database footprint for the active
    /// schema and page size.
    pub observed_bytes: u64,
}
